import type { Metadata } from "next";
import "./globals.css";
import {geistSans} from "@/lib/utils";


export const metadata: Metadata = {
  title: "OASES | Rentals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} flex flex-col justify-between m-0 antialiased`}
      >
        {children}
        {/* Footer */}
        <footer className="text-center w-full bg-black bottom-0 text-muted-foreground py-6 text-sm">
            © 2025 Oases, Inc.
        </footer>
      </body>
    </html>
  );
}
