import type {Metadata, Viewport} from "next";
import "./globals.css";
import {geistSans} from "@/lib/utils";
import ResponsiveHeader from "@/components/responsiive-header";


export const metadata: Metadata = {
  title: "OASES | Rentals",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    colorScheme: "dark",
    themeColor: "#000"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} flex flex-col justify-between m-0 antialiased`}
      >
      <ResponsiveHeader />
        {children}
        {/* Footer */}
        {/*<footer className="text-center w-full bg-[#262626] bottom-0 text-muted-foreground py-6 text-sm">*/}
        {/*    © 2025 Oases, Inc.*/}
        {/*</footer>*/}
      </body>
    </html>
  );
}
